# Publish the Nix flake outputs to Cachix
name: Cachix
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest]
    name: Publish Flake for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v12
      with:
        name: action-table
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Run Checks
      run: nix flake check -L --accept-flake-config

    - name: Build nix flake
      run: nix build -L --accept-flake-config ".#ci"

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-${{ matrix.os }} 
        path: result/bin/*

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: result/bin/*

  merge:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true


